-- INSERIMENTO DEI CORSI DI LAUREA TRIENNALE (Bachelor's Degree)
--

INSERT INTO degree (id, name, type, category) VALUES
('L33', 'Economia e Commercio', 'Bachelor''s Degree', 'Economics'),
('L18', 'Economia Aziendale e Digital Business', 'Bachelor''s Degree', 'Economics'),
('L7', 'Ingegneria Civile e Ambientale', 'Bachelor''s Degree', 'Enginering'),
('L8', 'Ingegneria Informatica, Elettronica e Videogame', 'Bachelor''s Degree', 'Enginering'),
('L9', 'Ingegneria Meccanica e per la Sostenibilità', 'Bachelor''s Degree', 'Enginering'),
('L23', 'Ingegneria Edile', 'Bachelor''s Degree', 'Enginering'),
('L9-L8', 'Ingegneria Gestionale (Interclasse)', 'Bachelor''s Degree', 'Enginering'),
('L13', 'Scienze Biologiche', 'Bachelor''s Degree', 'Science'),
('L32', 'Scienze Ambientali e Protezione Civile', 'Bachelor''s Degree', 'Science'),
('L22', 'Scienze Motorie per la Salute', 'Bachelor''s Degree', 'Science'),
('L25', 'Scienze Forestali e Ambientali / Sistemi Agricoli', 'Bachelor''s Degree', 'Agriculture'),
('L26', 'Scienze e Tecnologie Alimentari', 'Bachelor''s Degree', 'Agriculture'),
('LSNT1', 'Infermieristica e Ostetricia', 'Bachelor''s Degree', 'Medicine'),
('LSNT2', 'Fisioterapia e Logopedia', 'Bachelor''s Degree', 'Medicine'),
('LSNT3', 'Dietistica e Tecniche Sanitarie (varie)', 'Bachelor''s Degree', 'Medicine'),
('LSNT4', 'Tecniche della Prevenzione nell''Ambiente e nei Luoghi di Lavoro', 'Bachelor''s Degree', 'Medicine');

--
-- INSERIMENTO DEI CORSI DI LAUREA MAGISTRALE (Master's Degree)
--

INSERT INTO degree (id, name, type, category) VALUES
('LM77', 'Economia e Management / Management della Sostenibilità', 'Master''s Degree', 'Economics'),
('LM56', 'International Economics and Commerce / Data Science', 'Master''s Degree', 'Economics'),
('LM16', 'Scienze Economiche e Finanziarie', 'Master''s Degree', 'Economics'),
('LM21', 'Biomedical Engineering', 'Master''s Degree', 'Enginering'),
('LM23', 'Ingegneria Civile', 'Master''s Degree', 'Enginering'),
('LM24', 'Ingegneria Edile', 'Master''s Degree', 'Enginering'),
('LM29', 'Ingegneria Elettronica', 'Master''s Degree', 'Enginering'),
('LM30', 'Green Industrial Engineering', 'Master''s Degree', 'Enginering'),
('LM31', 'Ingegneria Gestionale', 'Master''s Degree', 'Enginering'),
('LM32', 'Ingegneria Informatica e dell''Automazione', 'Master''s Degree', 'Enginering'),
('LM33', 'Ingegneria Meccanica e Logistica', 'Master''s Degree', 'Enginering'),
('LM35', 'Environmental Engineering', 'Master''s Degree', 'Enginering'),
('LM6', 'Biologia Marina e Biologia Molecolare', 'Master''s Degree', 'Science'),
('LM75', 'Environmental Hazard and Disaster Risk Management', 'Master''s Degree', 'Science'),
('LM61', 'Scienze della Nutrizione e dell''Alimentazione', 'Master''s Degree', 'Science'),
('LM3', 'Paesaggio, Innovazione e Sostenibilità', 'Master''s Degree', 'Agriculture'),
('LM69', 'Scienze Agrarie e del Territorio', 'Master''s Degree', 'Agriculture'),
('LM70', 'Food and Beverage Innovation and Management', 'Master''s Degree', 'Agriculture'),
('LM73', 'Scienze e Tecnologie Forestali e Ambientali', 'Master''s Degree', 'Agriculture'),
('LMSN1', 'Scienze Infermieristiche ed Ostetriche', 'Master''s Degree', 'Medicine'),
('LMSN2', 'Scienze Riabilitative delle Professioni Sanitarie', 'Master''s Degree', 'Medicine');

--
-- INSERIMENTO DEI CORSI A CICLO UNICO (Single-Cycle Degree)
--

INSERT INTO degree (id, name, type, category) VALUES
('LM4CU', 'Ingegneria edile-architettura', 'Single-Cycle Degree', 'Enginering'),
('LM41', 'Medicina e Chirurgia / Medicine and Surgery', 'Single-Cycle Degree', 'Medicine'),
('LM46', 'Odontoiatria e Protesi Dentaria', 'Single-Cycle Degree', 'Medicine');

--
-- SEED: CORSI (per ogni degree: 8 obbligatori + 2 opzionali)
--

INSERT INTO course (degree_id, name, is_mandatory) VALUES
-- L33 (Economics)
('L33', 'Microeconomics', TRUE),
('L33', 'Macroeconomics', TRUE),
('L33', 'Statistics for Economics', TRUE),
('L33', 'Accounting Principles', TRUE),
('L33', 'Business Administration', TRUE),
('L33', 'Financial Mathematics', TRUE),
('L33', 'Marketing Fundamentals', TRUE),
('L33', 'International Economics', TRUE),
('L33', 'Advanced Corporate Finance', FALSE),
('L33', 'Entrepreneurship and Innovation', FALSE),

-- L18 (Economics)
('L18', 'Microeconomics', TRUE),
('L18', 'Macroeconomics', TRUE),
('L18', 'Statistics for Economics', TRUE),
('L18', 'Accounting Principles', TRUE),
('L18', 'Business Administration', TRUE),
('L18', 'Financial Mathematics', TRUE),
('L18', 'Marketing Fundamentals', TRUE),
('L18', 'International Economics', TRUE),
('L18', 'Advanced Corporate Finance', FALSE),
('L18', 'Entrepreneurship and Innovation', FALSE),

-- L7 (Engineering)
('L7', 'Calculus and Analytical Geometry', TRUE),
('L7', 'Physics for Engineers', TRUE),
('L7', 'Chemistry Fundamentals', TRUE),
('L7', 'Programming and Algorithms', TRUE),
('L7', 'Mechanics of Materials', TRUE),
('L7', 'Thermodynamics', TRUE),
('L7', 'Electrical Engineering Basics', TRUE),
('L7', 'Materials Science', TRUE),
('L7', 'Advanced Robotics', FALSE),
('L7', 'Renewable Energy Systems', FALSE),

-- L8 (Engineering)
('L8', 'Calculus and Analytical Geometry', TRUE),
('L8', 'Physics for Engineers', TRUE),
('L8', 'Chemistry Fundamentals', TRUE),
('L8', 'Programming and Algorithms', TRUE),
('L8', 'Mechanics of Materials', TRUE),
('L8', 'Thermodynamics', TRUE),
('L8', 'Electrical Engineering Basics', TRUE),
('L8', 'Materials Science', TRUE),
('L8', 'Advanced Robotics', FALSE),
('L8', 'Renewable Energy Systems', FALSE),

-- L9 (Engineering)
('L9', 'Calculus and Analytical Geometry', TRUE),
('L9', 'Physics for Engineers', TRUE),
('L9', 'Chemistry Fundamentals', TRUE),
('L9', 'Programming and Algorithms', TRUE),
('L9', 'Mechanics of Materials', TRUE),
('L9', 'Thermodynamics', TRUE),
('L9', 'Electrical Engineering Basics', TRUE),
('L9', 'Materials Science', TRUE),
('L9', 'Advanced Robotics', FALSE),
('L9', 'Renewable Energy Systems', FALSE),

-- L23 (Engineering)
('L23', 'Calculus and Analytical Geometry', TRUE),
('L23', 'Physics for Engineers', TRUE),
('L23', 'Chemistry Fundamentals', TRUE),
('L23', 'Programming and Algorithms', TRUE),
('L23', 'Mechanics of Materials', TRUE),
('L23', 'Thermodynamics', TRUE),
('L23', 'Electrical Engineering Basics', TRUE),
('L23', 'Materials Science', TRUE),
('L23', 'Advanced Robotics', FALSE),
('L23', 'Renewable Energy Systems', FALSE),

-- L9-L8 (Engineering)
('L9-L8', 'Calculus and Analytical Geometry', TRUE),
('L9-L8', 'Physics for Engineers', TRUE),
('L9-L8', 'Chemistry Fundamentals', TRUE),
('L9-L8', 'Programming and Algorithms', TRUE),
('L9-L8', 'Mechanics of Materials', TRUE),
('L9-L8', 'Thermodynamics', TRUE),
('L9-L8', 'Electrical Engineering Basics', TRUE),
('L9-L8', 'Materials Science', TRUE),
('L9-L8', 'Advanced Robotics', FALSE),
('L9-L8', 'Renewable Energy Systems', FALSE),

-- L13 (Science)
('L13', 'General Biology', TRUE),
('L13', 'General Chemistry', TRUE),
('L13', 'Physics Fundamentals', TRUE),
('L13', 'Mathematics for Sciences', TRUE),
('L13', 'Biochemistry', TRUE),
('L13', 'Molecular Biology', TRUE),
('L13', 'Ecology and Environment', TRUE),
('L13', 'Scientific Methodology', TRUE),
('L13', 'Advanced Genetics', FALSE),
('L13', 'Bioinformatics', FALSE),

-- L32 (Science)
('L32', 'General Biology', TRUE),
('L32', 'General Chemistry', TRUE),
('L32', 'Physics Fundamentals', TRUE),
('L32', 'Mathematics for Sciences', TRUE),
('L32', 'Biochemistry', TRUE),
('L32', 'Molecular Biology', TRUE),
('L32', 'Ecology and Environment', TRUE),
('L32', 'Scientific Methodology', TRUE),
('L32', 'Advanced Genetics', FALSE),
('L32', 'Bioinformatics', FALSE),

-- L22 (Science)
('L22', 'General Biology', TRUE),
('L22', 'General Chemistry', TRUE),
('L22', 'Physics Fundamentals', TRUE),
('L22', 'Mathematics for Sciences', TRUE),
('L22', 'Biochemistry', TRUE),
('L22', 'Molecular Biology', TRUE),
('L22', 'Ecology and Environment', TRUE),
('L22', 'Scientific Methodology', TRUE),
('L22', 'Advanced Genetics', FALSE),
('L22', 'Bioinformatics', FALSE),

-- L25 (Agriculture)
('L25', 'Agronomy and Crop Science', TRUE),
('L25', 'Soil Science and Management', TRUE),
('L25', 'Plant Biology', TRUE),
('L25', 'Agricultural Economics', TRUE),
('L25', 'Animal Science', TRUE),
('L25', 'Environmental Science', TRUE),
('L25', 'Food Technology', TRUE),
('L25', 'Sustainable Agriculture', TRUE),
('L25', 'Precision Farming', FALSE),
('L25', 'Agribusiness Management', FALSE),

-- L26 (Agriculture)
('L26', 'Agronomy and Crop Science', TRUE),
('L26', 'Soil Science and Management', TRUE),
('L26', 'Plant Biology', TRUE),
('L26', 'Agricultural Economics', TRUE),
('L26', 'Animal Science', TRUE),
('L26', 'Environmental Science', TRUE),
('L26', 'Food Technology', TRUE),
('L26', 'Sustainable Agriculture', TRUE),
('L26', 'Precision Farming', FALSE),
('L26', 'Agribusiness Management', FALSE),

-- LSNT1 (Medicine)
('LSNT1', 'Human Anatomy', TRUE),
('LSNT1', 'Physiology', TRUE),
('LSNT1', 'Biochemistry', TRUE),
('LSNT1', 'Microbiology', TRUE),
('LSNT1', 'Pathology', TRUE),
('LSNT1', 'Pharmacology', TRUE),
('LSNT1', 'Internal Medicine', TRUE),
('LSNT1', 'Surgery Fundamentals', TRUE),
('LSNT1', 'Advanced Clinical Practice', FALSE),
('LSNT1', 'Medical Research Methods', FALSE),

-- LSNT2 (Medicine)
('LSNT2', 'Human Anatomy', TRUE),
('LSNT2', 'Physiology', TRUE),
('LSNT2', 'Biochemistry', TRUE),
('LSNT2', 'Microbiology', TRUE),
('LSNT2', 'Pathology', TRUE),
('LSNT2', 'Pharmacology', TRUE),
('LSNT2', 'Internal Medicine', TRUE),
('LSNT2', 'Surgery Fundamentals', TRUE),
('LSNT2', 'Advanced Clinical Practice', FALSE),
('LSNT2', 'Medical Research Methods', FALSE),

-- LSNT3 (Medicine)
('LSNT3', 'Human Anatomy', TRUE),
('LSNT3', 'Physiology', TRUE),
('LSNT3', 'Biochemistry', TRUE),
('LSNT3', 'Microbiology', TRUE),
('LSNT3', 'Pathology', TRUE),
('LSNT3', 'Pharmacology', TRUE),
('LSNT3', 'Internal Medicine', TRUE),
('LSNT3', 'Surgery Fundamentals', TRUE),
('LSNT3', 'Advanced Clinical Practice', FALSE),
('LSNT3', 'Medical Research Methods', FALSE),

-- LSNT4 (Medicine)
('LSNT4', 'Human Anatomy', TRUE),
('LSNT4', 'Physiology', TRUE),
('LSNT4', 'Biochemistry', TRUE),
('LSNT4', 'Microbiology', TRUE),
('LSNT4', 'Pathology', TRUE),
('LSNT4', 'Pharmacology', TRUE),
('LSNT4', 'Internal Medicine', TRUE),
('LSNT4', 'Surgery Fundamentals', TRUE),
('LSNT4', 'Advanced Clinical Practice', FALSE),
('LSNT4', 'Medical Research Methods', FALSE),

-- LM77 (Economics)
('LM77', 'Advanced Microeconomics', TRUE),
('LM77', 'Advanced Macroeconomics', TRUE),
('LM77', 'Econometric Methods', TRUE),
('LM77', 'Corporate Finance', TRUE),
('LM77', 'Strategic Management', TRUE),
('LM77', 'International Trade', TRUE),
('LM77', 'Labor Economics', TRUE),
('LM77', 'Economic Policy', TRUE),
('LM77', 'Financial Risk Management', FALSE),
('LM77', 'Sustainable Business Practices', FALSE),

-- LM56 (Economics)
('LM56', 'Advanced Microeconomics', TRUE),
('LM56', 'Advanced Macroeconomics', TRUE),
('LM56', 'Econometric Methods', TRUE),
('LM56', 'Corporate Finance', TRUE),
('LM56', 'Strategic Management', TRUE),
('LM56', 'International Trade', TRUE),
('LM56', 'Labor Economics', TRUE),
('LM56', 'Economic Policy', TRUE),
('LM56', 'Financial Risk Management', FALSE),
('LM56', 'Sustainable Business Practices', FALSE),

-- LM16 (Economics)
('LM16', 'Advanced Microeconomics', TRUE),
('LM16', 'Advanced Macroeconomics', TRUE),
('LM16', 'Econometric Methods', TRUE),
('LM16', 'Corporate Finance', TRUE),
('LM16', 'Strategic Management', TRUE),
('LM16', 'International Trade', TRUE),
('LM16', 'Labor Economics', TRUE),
('LM16', 'Economic Policy', TRUE),
('LM16', 'Financial Risk Management', FALSE),
('LM16', 'Sustainable Business Practices', FALSE),

-- LM21 (Engineering)
('LM21', 'Advanced Calculus', TRUE),
('LM21', 'Quantum Physics', TRUE),
('LM21', 'Biomedical Engineering', TRUE),
('LM21', 'Biomechanics', TRUE),
('LM21', 'Medical Imaging', TRUE),
('LM21', 'Bioinformatics', TRUE),
('LM21', 'Clinical Engineering', TRUE),
('LM21', 'Regulatory Affairs', TRUE),
('LM21', 'Nanotechnology in Medicine', FALSE),
('LM21', 'Telemedicine Systems', FALSE),

-- LM23 (Engineering)
('LM23', 'Advanced Structural Analysis', TRUE),
('LM23', 'Geotechnical Engineering', TRUE),
('LM23', 'Construction Management', TRUE),
('LM23', 'Seismic Engineering', TRUE),
('LM23', 'Environmental Impact Assessment', TRUE),
('LM23', 'Urban Planning', TRUE),
('LM23', 'Building Information Modeling', TRUE),
('LM23', 'Sustainable Construction', TRUE),
('LM23', 'Advanced Concrete Technology', FALSE),
('LM23', 'Bridge Design', FALSE),

-- LM24 (Engineering)
('LM24', 'Advanced Structural Analysis', TRUE),
('LM24', 'Geotechnical Engineering', TRUE),
('LM24', 'Construction Management', TRUE),
('LM24', 'Seismic Engineering', TRUE),
('LM24', 'Environmental Impact Assessment', TRUE),
('LM24', 'Urban Planning', TRUE),
('LM24', 'Building Information Modeling', TRUE),
('LM24', 'Sustainable Construction', TRUE),
('LM24', 'Advanced Concrete Technology', FALSE),
('LM24', 'Bridge Design', FALSE),

-- LM29 (Engineering)
('LM29', 'Digital Signal Processing', TRUE),
('LM29', 'Control Systems', TRUE),
('LM29', 'Power Electronics', TRUE),
('LM29', 'Embedded Systems', TRUE),
('LM29', 'Communication Networks', TRUE),
('LM29', 'RF Engineering', TRUE),
('LM29', 'Microelectronics', TRUE),
('LM29', 'Electromagnetic Theory', TRUE),
('LM29', 'Wireless Sensor Networks', FALSE),
('LM29', 'IoT Applications', FALSE),

-- LM30 (Engineering)
('LM30', 'Industrial Processes', TRUE),
('LM30', 'Energy Systems', TRUE),
('LM30', 'Environmental Engineering', TRUE),
('LM30', 'Process Optimization', TRUE),
('LM30', 'Sustainable Technologies', TRUE),
('LM30', 'Quality Control', TRUE),
('LM30', 'Project Management', TRUE),
('LM30', 'Safety Engineering', TRUE),
('LM30', 'Circular Economy', FALSE),
('LM30', 'Carbon Footprint Analysis', FALSE),

-- LM31 (Engineering)
('LM31', 'Operations Research', TRUE),
('LM31', 'Supply Chain Management', TRUE),
('LM31', 'Quality Management', TRUE),
('LM31', 'Business Process Reengineering', TRUE),
('LM31', 'Decision Support Systems', TRUE),
('LM31', 'Lean Manufacturing', TRUE),
('LM31', 'Six Sigma', TRUE),
('LM31', 'Enterprise Resource Planning', TRUE),
('LM31', 'Digital Transformation', FALSE),
('LM31', 'Industry 4.0', FALSE),

-- LM32 (Engineering)
('LM32', 'Advanced Algorithms', TRUE),
('LM32', 'Software Engineering', TRUE),
('LM32', 'Database Systems', TRUE),
('LM32', 'Computer Networks', TRUE),
('LM32', 'Artificial Intelligence', TRUE),
('LM32', 'Cybersecurity', TRUE),
('LM32', 'Distributed Systems', TRUE),
('LM32', 'Human-Computer Interaction', TRUE),
('LM32', 'Machine Learning', FALSE),
('LM32', 'Blockchain Technology', FALSE),

-- LM33 (Engineering)
('LM33', 'Advanced Mechanics', TRUE),
('LM33', 'Manufacturing Processes', TRUE),
('LM33', 'CAD/CAM Systems', TRUE),
('LM33', 'Logistics Engineering', TRUE),
('LM33', 'Quality Assurance', TRUE),
('LM33', 'Maintenance Engineering', TRUE),
('LM33', 'Automation Systems', TRUE),
('LM33', 'Supply Chain Optimization', TRUE),
('LM33', 'Additive Manufacturing', FALSE),
('LM33', 'Smart Manufacturing', FALSE),

-- LM35 (Engineering)
('LM35', 'Environmental Chemistry', TRUE),
('LM35', 'Water Treatment', TRUE),
('LM35', 'Air Pollution Control', TRUE),
('LM35', 'Waste Management', TRUE),
('LM35', 'Environmental Impact', TRUE),
('LM35', 'Renewable Energy', TRUE),
('LM35', 'Climate Change Mitigation', TRUE),
('LM35', 'Sustainability Assessment', TRUE),
('LM35', 'Green Technologies', FALSE),
('LM35', 'Environmental Policy', FALSE),

-- LM6 (Science)
('LM6', 'Marine Biology', TRUE),
('LM6', 'Oceanography', TRUE),
('LM6', 'Molecular Genetics', TRUE),
('LM6', 'Ecosystem Dynamics', TRUE),
('LM6', 'Aquaculture', TRUE),
('LM6', 'Climate Change Biology', TRUE),
('LM6', 'Biodiversity Conservation', TRUE),
('LM6', 'Research Methodology', TRUE),
('LM6', 'Deep Sea Exploration', FALSE),
('LM6', 'Marine Biotechnology', FALSE),

-- LM75 (Science)
('LM75', 'Disaster Risk Assessment', TRUE),
('LM75', 'Environmental Hazards', TRUE),
('LM75', 'Climate Modeling', TRUE),
('LM75', 'Geospatial Analysis', TRUE),
('LM75', 'Emergency Management', TRUE),
('LM75', 'Vulnerability Analysis', TRUE),
('LM75', 'Sustainable Development', TRUE),
('LM75', 'Policy and Governance', TRUE),
('LM75', 'Remote Sensing', FALSE),
('LM75', 'Community Resilience', FALSE),

-- LM61 (Science)
('LM61', 'Advanced Nutrition', TRUE),
('LM61', 'Food Biochemistry', TRUE),
('LM61', 'Dietary Assessment', TRUE),
('LM61', 'Public Health Nutrition', TRUE),
('LM61', 'Clinical Nutrition', TRUE),
('LM61', 'Food Safety', TRUE),
('LM61', 'Nutritional Epidemiology', TRUE),
('LM61', 'Research in Nutrition', TRUE),
('LM61', 'Sports Nutrition', FALSE),
('LM61', 'Nutrigenomics', FALSE),

-- LM3 (Agriculture)
('LM3', 'Landscape Ecology', TRUE),
('LM3', 'Urban Green Spaces', TRUE),
('LM3', 'Sustainable Landscape Design', TRUE),
('LM3', 'Environmental Planning', TRUE),
('LM3', 'Biodiversity Management', TRUE),
('LM3', 'Climate Change Adaptation', TRUE),
('LM3', 'GIS for Landscape', TRUE),
('LM3', 'Policy and Legislation', TRUE),
('LM3', 'Restoration Ecology', FALSE),
('LM3', 'Cultural Landscapes', FALSE),

-- LM69 (Agriculture)
('LM69', 'Advanced Agronomy', TRUE),
('LM69', 'Precision Agriculture', TRUE),
('LM69', 'Crop Protection', TRUE),
('LM69', 'Soil Fertility Management', TRUE),
('LM69', 'Agricultural Biotechnology', TRUE),
('LM69', 'Farm Management', TRUE),
('LM69', 'Sustainable Farming', TRUE),
('LM69', 'Research Methods', TRUE),
('LM69', 'Organic Farming', FALSE),
('LM69', 'Agroforestry', FALSE),

-- LM70 (Agriculture)
('LM70', 'Food Innovation', TRUE),
('LM70', 'Beverage Technology', TRUE),
('LM70', 'Quality Control', TRUE),
('LM70', 'Supply Chain Management', TRUE),
('LM70', 'Sensory Analysis', TRUE),
('LM70', 'Food Safety Standards', TRUE),
('LM70', 'Marketing for Food', TRUE),
('LM70', 'Entrepreneurship in Food', TRUE),
('LM70', 'Sustainable Food Systems', FALSE),
('LM70', 'Product Development', FALSE),

-- LM73 (Agriculture)
('LM73', 'Forest Ecology', TRUE),
('LM73', 'Silviculture', TRUE),
('LM73', 'Forest Management', TRUE),
('LM73', 'Biodiversity in Forests', TRUE),
('LM73', 'Climate Change in Forests', TRUE),
('LM73', 'Remote Sensing for Forests', TRUE),
('LM73', 'Forest Policy', TRUE),
('LM73', 'Research in Forestry', TRUE),
('LM73', 'Urban Forestry', FALSE),
('LM73', 'Forest Certification', FALSE),

-- LMSN1 (Medicine)
('LMSN1', 'Advanced Clinical Practice', TRUE),
('LMSN1', 'Nursing Research', TRUE),
('LMSN1', 'Health Policy', TRUE),
('LMSN1', 'Patient Care Management', TRUE),
('LMSN1', 'Pharmacology for Nurses', TRUE),
('LMSN1', 'Mental Health Nursing', TRUE),
('LMSN1', 'Pediatric Nursing', TRUE),
('LMSN1', 'Geriatric Care', TRUE),
('LMSN1', 'Emergency Nursing', FALSE),
('LMSN1', 'Community Health Nursing', FALSE),

-- LMSN2 (Medicine)
('LMSN2', 'Rehabilitation Sciences', TRUE),
('LMSN2', 'Physical Therapy Techniques', TRUE),
('LMSN2', 'Occupational Therapy', TRUE),
('LMSN2', 'Speech Therapy', TRUE),
('LMSN2', 'Clinical Assessment', TRUE),
('LMSN2', 'Neurological Rehabilitation', TRUE),
('LMSN2', 'Sports Rehabilitation', TRUE),
('LMSN2', 'Research in Rehabilitation', TRUE),
('LMSN2', 'Pediatric Rehabilitation', FALSE),
('LMSN2', 'Geriatric Rehabilitation', FALSE),

-- LM4CU (Engineering)
('LM4CU', 'Architectural Design', TRUE),
('LM4CU', 'Structural Engineering', TRUE),
('LM4CU', 'Building Systems', TRUE),
('LM4CU', 'Urban Planning', TRUE),
('LM4CU', 'Construction Technology', TRUE),
('LM4CU', 'Environmental Design', TRUE),
('LM4CU', 'Project Management', TRUE),
('LM4CU', 'Professional Practice', TRUE),
('LM4CU', 'Sustainable Architecture', FALSE),
('LM4CU', 'Digital Design Tools', FALSE),

-- LM41 (Medicine)
('LM41', 'Human Anatomy and Physiology', TRUE),
('LM41', 'Biochemistry and Molecular Biology', TRUE),
('LM41', 'Pathology and Immunology', TRUE),
('LM41', 'Pharmacology and Toxicology', TRUE),
('LM41', 'Internal Medicine', TRUE),
('LM41', 'Surgery and Surgical Specialties', TRUE),
('LM41', 'Pediatrics and Gynecology', TRUE),
('LM41', 'Clinical Practice and Ethics', TRUE),
('LM41', 'Advanced Clinical Rotations', FALSE),
('LM41', 'Medical Research', FALSE),

-- LM46 (Medicine)
('LM46', 'Oral Anatomy and Physiology', TRUE),
('LM46', 'Dental Materials', TRUE),
('LM46', 'Oral Pathology', TRUE),
('LM46', 'Periodontology', TRUE),
('LM46', 'Endodontics', TRUE),
('LM46', 'Oral Surgery', TRUE),
('LM46', 'Prosthodontics', TRUE),
('LM46', 'Clinical Dentistry Practice', TRUE),
('LM46', 'Advanced Dental Techniques', FALSE),
('LM46', 'Dental Research', FALSE);